import type { Song } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const mockSongs: Song[] = [
  {
    id: '1',
    title: 'Midnight Drive',
    artist: 'Synthwave Dreamer',
    artistId: 'a1',
    coverUrl: PlaceHolderImages.find((p) => p.id === 'song-cover-6')?.imageUrl || '',
    audioUrl: '/audio/midnight-drive.mp3',
    genre: 'Synthwave',
    description: 'A retro-futuristic track for late-night drives.',
    likes: 1200,
  },
  {
    id: '2',
    title: 'Ocean Breath',
    artist: 'Ethereal Vibes',
    artistId: 'a2',
    coverUrl: PlaceHolderImages.find((p) => p.id === 'song-cover-1')?.imageUrl || '',
    audioUrl: '/audio/ocean-breath.mp3',
    genre: 'Ambient',
    description: 'Calming sounds of the ocean to help you relax.',
    likes: 3400,
  },
  {
    id: '3',
    title: 'City Lights',
    artist: 'Urban Groove',
    artistId: 'a3',
    coverUrl: PlaceHolderImages.find((p) => p.id === 'song-cover-3')?.imageUrl || '',
    audioUrl: '/audio/city-lights.mp3',
    genre: 'Lo-fi Hip Hop',
    description: 'A smooth beat for studying or chilling.',
    likes: 5600,
  },
  {
    id: '4',
    title: 'Forest Awakening',
    artist: "Nature's Melody",
    artistId: 'a4',
    coverUrl: PlaceHolderImages.find((p) => p.id === 'song-cover-4')?.imageUrl || '',
    audioUrl: '/audio/forest-awakening.mp3',
    genre: 'Chillstep',
    description: 'Waking up with the sounds of the forest.',
    likes: 850,
  },
  {
    id: '5',
    title: 'Geometric Dreams',
    artist: 'Pattern Master',
    artistId: 'a5',
    coverUrl: PlaceHolderImages.find((p) => p.id === 'song-cover-2')?.imageUrl || '',
    audioUrl: '/audio/geometric-dreams.mp3',
    genre: 'Electronic',
    description: 'A journey through sound and shapes.',
    likes: 2100,
  },
  {
    id: '6',
    title: 'Echoes in Monochrome',
    artist: 'The Visionaries',
    artistId: 'a6',
    coverUrl: PlaceHolderImages.find((p) => p.id === 'song-cover-5')?.imageUrl || '',
    audioUrl: '/audio/echoes-in-monochrome.mp3',
    genre: 'Indie Rock',
    description: 'Reflective and moody indie rock.',
    likes: 980,
  },
];
