
import type { Song, User } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Ginjin',
    artistId: 'a1',
    bio: 'Rapper from Ulaanbaatar, bringing the fire from the streets to your speakers. Stay tuned for more heat.',
    profilePictureUrl: 'https://picsum.photos/seed/u1/200/200',
  },
  {
    id: 'u2',
    name: 'Fla',
    artistId: 'a2',
    bio: 'Smooth R&B and soul singer. My music is all about vibes and connecting with you.',
    profilePictureUrl: 'https://picsum.photos/seed/u2/200/200',
  },
  {
    id: 'u3',
    name: 'Lil Thug E',
    artistId: 'a3',
    bio: 'Hip Hop artist making waves. My tracks are for the confident and the bold. Big steppin only.',
    profilePictureUrl: 'https://picsum.photos/seed/u3/200/200',
  },
  {
    id: 'u4',
    name: 'Mrs M',
    artistId: 'a4',
    bio: 'Pop singer and songwriter. I pour my heart into every song. Follow my journey.',
    profilePictureUrl: 'https://picsum.photos/seed/u4/200/200',
  },
    {
    id: 'u5',
    name: '168',
    artistId: 'a5',
    bio: 'Rap artist speaking my truth. My music is a tribute to the important things in life.',
    profilePictureUrl: 'https://picsum.photos/seed/u5/200/200',
  },
  {
    id: 'u6',
    name: 'Cili',
    artistId: 'a6',
    bio: 'Indie artist creating dreamy soundscapes. Perfect for rainy days and thoughtful moments.',
    profilePictureUrl: 'https://picsum.photos/seed/u6/200/200',
  },
];

export const mockSongs: Song[] = [
  {
    id: '1',
    title: 'Chotgor',
    artist: 'Ginjin',
    artistId: 'a1',
    coverUrl: PlaceHolderImages.find((p) => p.id === 'song-cover-6')?.imageUrl || '',
    audioUrl: '/audio/midnight-drive.mp3',
    genre: 'Rap',
    description: 'Hard-hitting rap from the heart of Ulaanbaatar.',
    likes: 1500,
    isPublic: true,
    likedByUser: false,
  },
  {
    id: '2',
    title: 'Nobody',
    artist: 'Fla',
    artistId: 'a2',
    coverUrl: PlaceHolderImages.find((p) => p.id === 'song-cover-1')?.imageUrl || '',
    audioUrl: '/audio/ocean-breath.mp3',
    genre: 'R&B',
    description: 'Smooth R&B vibes for a chill evening.',
    likes: 2800,
    isPublic: true,
    likedByUser: true,
  },
  {
    id: '3',
    title: 'Big Steppin',
    artist: 'Lil Thug E',
    artistId: 'a3',
    coverUrl: PlaceHolderImages.find((p) => p.id === 'song-cover-3')?.imageUrl || '',
    audioUrl: '/audio/city-lights.mp3',
    genre: 'Hip Hop',
    description: 'A confident hip-hop track with a heavy beat.',
    likes: 4200,
    isPublic: true,
    likedByUser: false,
  },
  {
    id: '4',
    title: 'Zurhend Gants',
    artist: 'Mrs M',
    artistId: 'a4',
    coverUrl: PlaceHolderImages.find((p) => p.id === 'song-cover-4')?.imageUrl || '',
    audioUrl: '/audio/forest-awakening.mp3',
    genre: 'Pop',
    description: 'An emotional pop ballad about love.',
    likes: 950,
    isPublic: false,
    likedByUser: false,
  },
  {
    id: '5',
    title: 'Aav, Eej',
    artist: '168',
    artistId: 'a5',
    coverUrl: PlaceHolderImages.find((p) => p.id === 'song-cover-2')?.imageUrl || '',
    audioUrl: '/audio/geometric-dreams.mp3',
    genre: 'Rap',
    description: 'A tribute to parents and family.',
    likes: 3100,
    isPublic: true,
    likedByUser: false,
  },
  {
    id: '6',
    title: 'Borootei',
    artist: 'Cili',
    artistId: 'a6',
    coverUrl: PlaceHolderImages.find((p) => p.id === 'song-cover-5')?.imageUrl || '',
    audioUrl: '/audio/echoes-in-monochrome.mp3',
    genre: 'Indie',
    description: 'Dreamy indie track for a rainy day.',
    likes: 1100,
    isPublic: true,
    likedByUser: true,
  },
];
